const goods=[['Cocaine',38000,47000],['Crack',20000,28000],['Heroin',10000,19000],['Acid',1000,3000],['Angel Dust',1000,2000],['Crystal',500,1100],['Meth',500,1000],['Grass',100,350],['Speed',40,120],['Ludes',1,25]];
const campusNames=['Illinois','Indiana','Iowa','Maryland','Michigan','Michigan State','Minnesota','Nebraska','Northwestern','Ohio State','Oregon','Penn State','Purdue','Rutgers','UCLA','USC','Washington','Wisconsin'];
const baseSecurity=[55,45,50,65,70,60,55,40,80,75,35,60,55,70,65,75,40,50];
const baseAcademics=[92,90,91,93,96,92,93,90,97,94,92,94,93,95,96,94,95,94];
const $=s=>document.querySelector(s), money=n=>'$'+Math.floor(n).toLocaleString(), rnd=(a,b)=>Math.floor(Math.random()*(b-a+1))+a;
function fresh(){return{day:1,loc:rnd(0,17),health:100,cash:500,bank:250,debt:0,loan:0,holdMax:10,hold:Array(10).fill(0),status:1,guns:1,riots:0,prices:[],campuses:campusNames.map((name,i)=>({name,security:baseSecurity[i],academics:baseAcademics[i],riot:rnd(10,35),anarchy:false,bonus:0}))}}
let g; try{g=JSON.parse(localStorage.pimpWyldWeb)||fresh()}catch{g=fresh()} if(!g.campuses)g=fresh();
function save(){localStorage.pimpWyldWeb=JSON.stringify(g)} function used(){return g.hold.reduce((a,b)=>a+b,0)} function campus(){return g.campuses[g.loc]}
function prices(){g.prices=goods.map(x=>Math.max(1,Math.floor(rnd(x[1],x[2])*(1.25-campus().security*.005)*rnd(90,110)/100)))} if(!g.prices.length)prices();
function msg(t,kind=''){ $('#message').innerHTML=`<span class="${kind}">${t}</span>` }
function buttons(list){$('#actions').innerHTML=list.map(([label,fn,primary])=>`<button ${primary?'class="primary"':''} data-fn="${fn}">${label}</button>`).join('')}
function render(){const c=campus();$('#dayLabel').textContent=`DAY ${g.day}/60 · ${c.name}`;$('#marketRows').innerHTML=goods.map((x,i)=>`<div class="row"><span>${String.fromCharCode(65+i)} · ${x[0]}</span><span class="price">${money(g.prices[i])}${c.bonus?' ×2 SELL':''}</span><span class="held">${g.hold[i]}</span></div>`).join('');$('#statusRows').innerHTML=[["Cash",money(g.cash)],["Bank",money(g.bank)],["Debt",money(g.debt)],["Health",g.health+'/100'],["Hold",used()+'/'+g.holdMax],["Status",g.status],["Guns",g.guns],["Control",c.anarchy?'ANARCHY':'ORDER'],["Riot",c.riot+'%'],["Security",c.security],["Academics",c.academics]].map(x=>`<div class="row"><span>${x[0]}</span><span>${x[1]}</span></div>`).join('');buttons([['BUY','buy'],['SELL','sell'],['DRIVE','drive'],['RIOT','riot',1],['HOSPITAL','hospital'],['LOAN','loan']]);save()}
function chooseGood(mode){msg(`${mode==='buy'?'BUY':'SELL'} — choose a market. ${mode==='buy'?`Hold space: ${g.holdMax-used()}.`:''}`);buttons(goods.map((x,i)=>[`${String.fromCharCode(65+i)} ${x[0]}`,`${mode}:${i}`]).concat([['BACK','home']]))}
function trade(mode,i){let max=mode==='buy'?Math.min(g.holdMax-used(),Math.floor(g.cash/g.prices[i])):g.hold[i];let n=Number(prompt(`${mode.toUpperCase()} ${goods[i][0]} — maximum ${max}:`,max));if(!Number.isFinite(n)||n<1)return render();n=Math.min(Math.floor(n),max);let total=n*g.prices[i]*(mode==='sell'&&campus().bonus?2:1);if(mode==='buy'){g.cash-=total;g.hold[i]+=n}else{g.cash+=total;g.hold[i]-=n}if(campus().bonus)campus().bonus--;msg(`${mode==='buy'?'Bought':'Sold'} ${n} ${goods[i][0]} for ${money(total)}.`, 'good');render()}
function drive(){msg('Choose your next campus. Travel costs $5 and spends one day.');buttons(g.campuses.map((c,i)=>[c.name+(c.anarchy?' · ANARCHY':''),`go:${i}`]).concat([['BACK','home']]))}
function go(i){if(i===g.loc)return render();if(g.cash<5){msg('You need $5 to travel.','danger');return render()}g.cash-=5;g.loc=i;g.day++;if(g.debt){g.debt=Math.floor(g.debt*1.1);if(g.loan>0)g.loan--;else{g.health-=10;msg('The overdue loan costs you 10 health.','danger')}}prices();if(Math.random()<Math.min(.3,.08+g.riots*.02))return ambush();msg(`Arrived at ${campus().name}.`, 'good');endTurn()}
function ambush(){msg(`AMBUSH! You have ${g.guns} gun${g.guns===1?'':'s'}. Fight or escape?`,'danger');buttons(g.guns?[['FIGHT','fight',1],['ESCAPE','escape']]:[['ESCAPE','escape',1]])}
function fight(){let win=rnd(1,100)<=55+g.guns*12+g.status;if(win){let loot=rnd(75,300);g.cash+=loot;g.status++;msg(`You fight them off and recover ${money(loot)}.`, 'good')}else{let hit=rnd(8,25);g.health-=hit;msg(`They overpower you. You lose ${hit} health.`, 'danger')}endTurn()}
function escape(){if(rnd(1,100)<=60)msg('You break away and escape.','good');else{g.health-=10;msg('They cut you off. You lose 10 health.','danger')}endTurn()}
function riot(){let c=campus();if(c.anarchy){msg('This campus is already in anarchy.');return render()}g.day++;g.riots++;if(c.riot<60){let gain=rnd(10,20);c.riot=Math.min(100,c.riot+gain);msg(`You organize the crowd. Riot +${gain}. The action spends one day.`,'good');return endTurn()}let win=rnd(1,100)<=45+g.status+c.riot/4+g.guns*8-c.security/3;if(win){c.anarchy=true;c.security=0;c.academics=0;c.riot=0;c.bonus=2;g.status+=10;msg(`${c.name} falls into ANARCHY! Security and academics hit 0. Drug sales pay double for two turns.`,'good')}else{let hit=rnd(8,22);g.health-=hit;msg(`The riot fails. You lose ${hit} health. The action spends one day.`,'danger')}endTurn()}
function hospital(){let missing=100-g.health;if(!missing){msg('The nurse says you are already at full health.');return render()}let heal=Math.min(missing,Math.floor(g.cash/4));if(!heal){msg('Treatment is $4 per health point. You cannot afford it.','danger');return render()}let cost=heal*4;if(confirm(`Restore ${heal} health for ${money(cost)}?`)){g.cash-=cost;g.health+=heal;msg(`Treatment complete. Health ${g.health}/100.`, 'good')}render()}
function loan(){if(g.debt){let pay=Math.min(g.debt,g.cash);let n=Number(prompt(`Debt: ${money(g.debt)}. Pay how much?`,pay));if(n>0){n=Math.min(n,pay);g.cash-=n;g.debt-=n;if(!g.debt)g.loan=0;msg(`Paid ${money(n)}.`,'good')}}else{let n=Number(prompt(`Take a loan (maximum ${money(500+g.status*250)}):`,500));if(n>0&&n<=500+g.status*250){g.cash+=n;g.debt=n;g.loan=5;msg('Five campus visits until health penalties begin.','danger')}}render()}
function endTurn(){if(g.health<=0||g.day>60){msg(g.health<=0?'Your campaign is over.':'Day 60 is over. Campaign complete.','danger');buttons([['NEW GAME','reset',1]]);save()}else render()}
function act(fn){if(fn==='home')return render();if(fn==='buy'||fn==='sell')return chooseGood(fn);if(fn==='drive')return drive();if(fn==='riot')return riot();if(fn==='hospital')return hospital();if(fn==='loan')return loan();if(fn==='fight')return fight();if(fn==='escape')return escape();if(fn==='reset'){g=fresh();prices();msg('A new 60-day campaign begins.');return render()}let [a,b]=fn.split(':');if(a==='buy'||a==='sell')trade(a,+b);if(a==='go')go(+b)}
$('#actions').addEventListener('click',e=>{let b=e.target.closest('button');if(b)act(b.dataset.fn)});$('#resetBtn').onclick=()=>{if(confirm('Start a new game?'))act('reset')};document.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA'].includes(e.target.tagName))return;let k=e.key.toLowerCase();let map={b:'buy',s:'sell',d:'drive',r:'riot',h:'hospital',l:'loan',escape:'home'};if(map[k]){e.preventDefault();act(map[k])}});msg('Choose an action. Your progress saves automatically.');render();
